### ISSUE TITLE
[vue-loader] vue-template-compiler must be installed as a peer dependency, or a compatible compiler implementation must be passed via options.

### ISSUE THREAD

**Issue by HankBrown** [hawkeye64/electron-quasar-file-explorer#3] opened 2019-04-25 19:38 UTC
Vigorous hand clapping and thumbs up on  your tutorial. You are a talented writer.
Thank you for sharing your work.

Build error:
```
Module build failed (from ./node_modules/vue-loader/lib/index.js):
  Error: [vue-loader] vue-template-compiler must be installed as a peer dependency, or a compatible compiler implementation must be passed via options.
```
Possible solutions:

https://myquickfix.co.uk/2019/01/08/fixing-vue-loader-vue-template-compiler-must-be-installed-as-a-peer-dependency/

https://medium.com/@nchutchind/i-ended-up-getting-the-following-error-vue-loader-vue-template-compiler-must-be-installed-as-a-37e8c007c1cc

But in my case...
```
$ npm show vue-template-compiler version
2.6.10
$ npm show vue version
2.6.10
```

I suppose this is related to the latest release  of quasar. I see another having the same issue...

(https://forum.quasar-framework.org/topic/3110/fresh-install-of-quasar-cli-and-quasar-dev-won-t-work/4)

My webpack fu is not good enough to truly understand what is required of me here.

**Later:**

npm install --dev vue-template-compiler

That got me past this error. There are more issues but they were self-explanatory. The final build has "critical" errors but ran and behaved.

**Comment by hawkeye64** [comment] 2019-04-25 20:16
Thanks for figuring this out. I'll be taking a look at it on the weekend.

**Comment by hawkeye64** [comment] 2019-04-29 12:54
I pulled a new clone and built without issue. I believe the problem here was that you likely used `npm` to build and we have definitive proof that `npm` has issues with local packages and dependencies. It is recommended to install `yarn`, remove your `node_modules` folder, run `yarn`, then run `yarn dev`.

Would you be so helpful and try out these steps? Thanks.

**Comment by HankBrown** [comment] 2019-04-29 15:16
Have just recently switched from npm to https://verdaccio.org/
But I read it should not make a difference.
Tried again with npm (hey ya never know), same result.

Installed yarn. Don't like using brew on a mac and sure enough it gave me all kinds of warnings and required me to re-install node. Saved all that output and need to crawl over it to maybe spot a helpful message.

Eventually I think I am ok...

```
$ yarn --version
1.15.2
$ node --version
v10.15.3
```

Fail to run. Then I notice you said "yarn dev". That gets me further. Now it looks like it did last week. I have the electron app running and can navigate the file system. But it is has problems.

Both npm and yarn say:

```
This dependency was not found:

* aws-sdk in ./node_modules/fsevents/node_modules/node-pre-gyp/lib/info.js, ./node_modules/fsevents/node_modules/node-pre-gyp/lib/publish.js and 1 other
```
... but yarn installs it okay.

The runtime error is:

```
WARNING in ./node_modules/electron-debug/index.js 81:45-58
Critical dependency: the request of a dependency is an expression
 @ ./src-electron/main-process/electron-main.dev.js
 @ multi ./src-electron/main-process/electron-main.dev.js

WARNING in ./node_modules/electron-debug/index.js 84:85-106
Critical dependency: the request of a dependency is an expression
 @ ./src-electron/main-process/electron-main.dev.js
 @ multi ./src-electron/main-process/electron-main.dev.js

 app:electron Booting up Electron process... +2ms
 app:spawn Running "/Users/brownhanky/home/brownhanky/bhjs/FEXPLORE/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron --inspect=5858 /Users/brownhanky/home/brownhanky/bhjs/FEXPLORE/.quasar/electron/electron-main.js" +1ms

Debugger listening on ws://127.0.0.1:5858/c202a730-7681-4e2a-87ba-6d658ffca906
For help, see: https://nodejs.org/en/docs/inspector
2019-04-29 07:42:42.516 Electron Helper[21134:589154] Couldn't set selectedTextBackgroundColor from default ()
```
The console messages are many (attached). node-gyp is some kind of problem child.

So I don't know. Have I got something messed up in yarn/brew/node/npm/verdaccio ?
Could easily be. I'm not able to find and fix that fast. I must call in help.

I attach a log of what I did with screen prints.

This may not be a big deal, my experience with these package tools is very very limited, and I'm no expert in vue, quasar and electron. Nor are my problems yours to resolve. I leave you with the log and screen prints, I won't know more until my guru returns late this week, or I make time to investigate further. Today time is limited.  Thank you for the update.
<img width="506" alt="YARN-CON-1" src="https://user-images.githubusercontent.com/1131363/56906397-0334c600-6a57-11e9-81d3-7c6d8e6ba019.png">
<img width="513" alt="YARN-CON-2" src="https://user-images.githubusercontent.com/1131363/56906398-0334c600-6a57-11e9-857b-c3a9f76810c1.png">
<img width="512" alt="YARN-CON-3" src="https://user-images.githubusercontent.com/1131363/56906399-0334c600-6a57-11e9-9d5c-abf58fa98cce.png">
<img width="1429" alt="YARN-DEV FEXPLORE 2019 04 29" src="https://user-images.githubusercontent.com/1131363/56906401-0334c600-6a57-11e9-97ff-c047d180d513.png">
[YARN.FEXPLORE.2019.04.29.txt](https://github.com/hawkeye64/electron-quasar-file-explorer/files/3128004/YARN.FEXPLORE.2019.04.29.txt)

**Comment by hawkeye64** [comment] 2019-04-30 16:28
Yeah, that's ugly.
node-gyp is a cross-platform command-line tool written in Node.js for compiling native addon modules for Node.js, which takes away the pain of dealing with the various differences in build platforms.
If that's having issues then there is something going on deeper here.
Possibly C++ libraries that it needs available on the local system to build whatever is needed into node.
I'm really not an expert in that at all.

**Comment by hawkeye64** [comment] 2019-04-30 16:39
try these steps:
1. `npm i --dev vue-template-compiler`
2. quasar clean
3. `npm run dev`
See if that works out for you

**Comment by hawkeye64** [comment] 2019-05-13 07:44
I merged in #1 which should fix this issue. Can you test, and if it works close this issue. If it doesn't work out for you, let me know.

**Comment by HankBrown** [comment] 2019-05-13 14:19
Module build failed (from ./node_modules/vue-loader/lib/index.js):
  Error: [vue-loader] vue-template-compiler must be installed as a peer dependency, or a compatible compiler implementation must be passed via options.

I killed over an hour, reinstalling node and yarn and various.
I can make no sense of this. It is above my pay grade

I gave it to my vue developer. Fresh machine. He also failed.

Aggravating. No idea, sorry. I saved a text file of everything I ran if you want to see it.
But this is going nowhere for me and I must move on.

Pretty sure I have valid installs for yarn, node and npm now.
But something must be mis-configured.

I didn't quite understand changing the code change for "Any drawback to adding that so that it works with NPM?", did it anyway, no joy.

Sorry I can't be more helpful. This is a disappointment for me and a constant worry now for dependency hell. I don't want to waste your time if this is my machine/config.

Close the issue if you can't deal with it. I won't ask for more of your time.

**Comment by hawkeye64** [comment] 2020-10-18 17:26
This package has been updated to use Quasar v1.14.1and Electron 10. The issue is no longer relevant.

**Closed by hawkeye64** 2020-10-18 17:26 UTC
